[tool.poetry]
name = "tdx-data-processor"
version = "0.1.0"
description = "一个使用pytdx读取本地股票数据并存储到数据库或CSV的程序"
authors = ["我如此拉风 <xbfighting@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytdx = "^1.72"
pandas = "^2.2.3"
sqlalchemy = "^2.0.40"
tqdm = "^4.67.1"
python-dotenv = "^1.1.0"
pymysql = "^1.1.1"
psycopg2-binary = "^2.9.10"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
priority = "default"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
